version: "3"
services:
    pdf-api:
        restart: unless-stopped
        # build:
        #   context: .
        #   dockerfile: Dockerfile
        image: rolandihms/html-pdf-api
        container_name: pdf-api
        volumes:
            - ./public:/public/
        # environment:
        #   WKHTMLTOPDF_PATH: ${WKHTMLTOPDF_PATH}
        #   PORT: ${PORT}
        ports:
            - "3005:3000"
        networks:
            - nginx-proxy
networks:
  nginx-proxy:
    external: true